# Development profile

app:
  version: @project.version@
  api:
    version: 'v1'
  security:
    jwt:
      secret: "asldfwef093rqefalsdslslfWERWEWE"
      expiration: 7 #Days
      refresh-expiration: 14 #Days

# Spring properties
spring:
  application:
    name: flight-advisor-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # Database configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/flights
    username: postgres
    password: postgres
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        # Switching on batch insert
        # Take the time to group inserts by entity, creating larger batches.
        order_inserts: true
        order_updates: true
        # collect inserts in batches of 100
        jdbc:
          size: 100
#  sql:
#    init:
#      data-locations: classpath*:db/data.sql
#      schema-locations: classpath*:db/schema.sql
#      platform: postgresql
#      mode: always

# Server configs
server:
  port: 8090
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /flight-api

# Application health and information management
management:
  info.git:
    mode: full
    enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: false
    health.show-details: always

# Logging settings
logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    springframework:
      cache: trace
      web: debug
  io:
    rxs:
      flights: debug
  web: debug
  root: info

# OpenAPI (Swagger) settings
springdoc:
  # swagger-ui custom path
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  # to display the actuator endpoints.
  show-actuator: false
