# Production profile
app:
    allowedOrigins: 'http://localhost:4200'

spring:
    jmx:
        enabled: false
    # Database configurations
    datasource:
        url: jdbc:h2:./db/flightDB
        password: Admin1234
    jpa:
        properties:
            hibernate:
                generate_statistics: false
    sql:
        init:
            data-locations: classpath*:db/prod/data.sql

logging.level:
    org:
        hibernate:
            SQL: info
            type.descriptor.sql.BasicBinder: info
        springframework:
            cache: info
            web: debug
        siriusxi:
            fa: debug
    web: debug
    root: info
